project uploaded
Zzzenk/article_generator pull request #3
Opened 2023-04-17 19:01 UTC by Zzzenk

2023-04-18 19:00 UTC, OtezVikentiy requested changes

2023-04-18 19:00 UTC, OtezVikentiy commented on src/Security/EmailVerifier.php
> +use SymfonyCasts\Bundle\VerifyEmail\Exception\VerifyEmailExceptionInterface;
Честно говоря использовать бандлы для такого простого функционала как подтверждение email - имхо это прям грешно... В целом готовые решения стоит использовать лишь тогда, когда там функционала прям очень много и писать самостоятельно прям долго и лень. А вот в случае с подтверждением почты... Ну... Как бы... функционала на 3 копейки, а дыра в безопасности потенциально может быть большой.

2023-04-19 06:21 UTC, Zzzenk commented on src/Controller/DashboardController.php
> +            $disabled = 'disabled';
Это строка для отключения полей input:
`<input type="text" id="title" name="title" class="form-control" placeholder="Название шаблона" required {{ disabled }}>`

2023-04-19 06:25 UTC, Zzzenk commented on src/Controller/MainController.php
> +                $disabled = 'disabled';
Также строка для отключения input

2023-04-19 06:38 UTC, Zzzenk commented on src/Controller/DashboardController.php
> +            $disabled = 'disabled';
Заменил на твиговскую проверку

2023-04-19 13:50 UTC, Zzzenk commented on src/Repository/ModuleRepository.php
> +    <img class="mr-3" src="{{ image }}" width="250" height="250" alt="">
Это дефолтные шаблоны для генерации статей, если у пользователя не задоно своих. Где их лучше хранить? Не создавать же отдельную сущность под это

2023-04-19 15:12 UTC, Zzzenk commented on src/Repository/UserRepository.php
> +    public function checkSubscription($token)
В отдельный сервис вынес.
Про роли понял, на будущее учту.
Сделал так, исходя из принципа KISS - таким способом получить знаение подписки пользователя проще всего, даже не нужно отдельных методов писать)
На текущем учебном проекте уже не буду переделывать наверное. Ну или потом, пока сосредоточусь на другой оптимизации.

2023-04-19 19:48 UTC, OtezVikentiy commented on src/Repository/ModuleRepository.php
> +    <img class="mr-3" src="{{ image }}" width="250" height="250" alt="">
1) убрать весь html код в твиг
2) роуты до твигов - в константу

2023-04-19 19:49 UTC, OtezVikentiy commented on src/Repository/UserRepository.php
> +    public function checkSubscription($token)
окай

2023-04-20 20:48 UTC, OtezVikentiy requested changes

2023-04-21 05:41 UTC, Zzzenk commented on src/Entity/ApiToken.php
> +        private readonly ProfileUpdateService $profileUpdateService
В таком случае у меня так и останется генерация токена в двух местах:

**ApiToken** - для регистрации пользователя
```    public function __construct(?User $user)
    {
        $this->user = $user;
        $this->token = sha1(uniqid('token'));
    }
```

**ProfileUpdateService** для генерации новых токенов
```
    public function generateNewToken(): string
    {
        return sha1(uniqid('token'));
    }
```

Я не знаю как сделать по другому

2023-04-21 06:04 UTC, Zzzenk commented on src/Service/ModuleService.php
> +        $qb = $this->em->createQueryBuilder();
Так в конструкторе итак он:
`private readonly EntityManagerInterface $em`

2023-04-21 17:06 UTC, OtezVikentiy commented on src/Controller/DashboardController.php
> +        $this->addFlash('success', 'Шаблон успешно добавлен');
Я вообще больше приверженец SPA и работы через AJAX'ы с фронтом.
А через сессию... Ну не сказать, что это прям плохо, я просто крайне редко встречаю такие реализации на самом деле... И мне кажется что местами это может как-то крякнуть в неправильном месте например если будет пересечение ключей - у тебя может отображаться какая-то плашка где-то которая не должна или что-то подобное.
Обычно это реализуется именно на основании ответа сервера по той причине, что это одноразовый и конечный процесс. Пришел ответ - показали окно, закрыли и всё... нигде больше меток не хранится, а в случае с сессией - метка будет продолжать храниться дальше до закрытия сессии.

2023-04-21 17:08 UTC, OtezVikentiy commented on src/Service/ModuleService.php
> +        $qb = $this->em->createQueryBuilder();
я имею в виду. что переделать на получение репозитория и использование его стандартных методов, а не строить запросы нативные. ))) У тебя эта операция совершенно спокойно делается поиском записи и ее удалением через $this->em->remove. Это более читабельная операция.

2023-04-21 19:17 UTC, merged